package io.github.try2love.codexbridge;
import android.content.Context;
final class MobileStrings {
 private static final java.util.Map<String,String> values=new java.util.HashMap<>();
 static {
values.put("Codex 未完成侧边聊天操作，请检查模型接入和运行时版本","Codex could not complete the side chat operation. Check the model connection and runtime version.");
values.put("临时侧边聊天数量已达上限，请关闭不用的聊天；必要时重启网关","Too many temporary side chats. End unused chats or restart the gateway.");
values.put("侧边聊天工作目录不一致，已取消创建","Side chat creation cancelled because the working directory did not match.");
values.put("侧边聊天已关闭或失效","Side chat closed or expired");
values.put("侧边聊天已失效，请关闭后新建","Side chat expired. End it and create a new one.");
values.put("侧边聊天执行失败，请检查模型接入后重试","Side chat failed. Check the model connection and try again.");
values.put("侧边聊天操作结果未确认，请刷新状态，不要重复发送","Operation unconfirmed. Refresh the status before sending again.");
values.put("侧边聊天的模型接入与主聊天不一致，已取消创建","Side chat creation cancelled because its model connection did not match the parent.");
values.put("侧边聊天运行时已断开","Side chat runtime disconnected");
values.put("同一消息标识不能用于不同内容","A message ID cannot be reused for different content");
values.put("无效侧边聊天操作","Invalid side chat operation");
values.put("无法确认临时分支，已取消创建","Could not verify the temporary branch. Creation cancelled.");
values.put("模型 ID 格式不正确","Invalid model ID");
values.put("此 Codex 运行时不支持临时侧边聊天，请更新 Codex","This runtime does not support temporary side chats. Update Codex.");
values.put("此侧边聊天已关闭或已失效，请刷新标签","Side chat closed or expired. Refresh this tab.");
values.put("此次创建的侧边聊天已关闭，请重新打开标签后新建","This side chat was ended. Reopen the tab to create another.");
values.put("此请求已处理或已失效","This request was handled or expired");
values.put("此请求暂不支持在侧边聊天处理，请停止本次回复。","This request is not supported in side chats. Stop this response.");
values.put("此请求暂不支持，请停止本次回复","Unsupported request. Stop this response.");
values.put("此预览暂支持网关电脑上的聊天，SSH 远程工作区尚未接入侧边聊天","Side chats currently support the gateway computer. SSH remote workspaces are not supported yet.");
values.put("确认回复格式不正确","Invalid approval response");
values.put("确认操作无效","Invalid approval action");
values.put("请先等待回复完成或处理确认请求","Wait for the response or handle the pending request first");
values.put("请输入 1–20000 字的消息","Enter a message of 1\u201320,000 characters");
values.put("请选择有效的推理强度","Choose a valid reasoning effort");
values.put("请选择本次允许、拒绝或取消","Choose allow once, deny or cancel");
values.put("请选择本次允许或拒绝","Choose allow once or deny");
values.put("这个模型不支持所选推理强度","This model does not support the selected reasoning effort");
values.put("公网地址必须使用 HTTPS；HTTP 仅限局域网","Public addresses require HTTPS. HTTP is only allowed on a local network.");
values.put("网关地址不应包含路径","Gateway addresses must not include a path");
values.put("请使用电脑网关提供的地址或二维码","Use the address or QR code from your computer\u2019s gateway");
values.put("请填写完整网关地址，不含账号或参数","Enter a complete gateway address without credentials or query parameters");
values.put("请填写完整的 HTTPS 网关地址，或局域网 HTTP 地址，不含路径、账号和参数。","Enter a complete HTTPS gateway address, or a local HTTP address, without a path, credentials or parameters.");
  values.put("通知收件箱","Notification inbox");
  values.put("手机设置","Mobile settings");
  values.put("返回电脑列表","Back to computers");
  values.put("账号与接入","Accounts and connections");
  values.put("外观与显示","Appearance");
  values.put("刷新页面","Reload page");
  values.put("好","OK");
  values.put("电脑上的工作，\n带在身边。","Your computer’s work,\nalways with you.");
  values.put("继续聊天、查看结果，让电脑替你运行。","Continue chats and view results while your computer does the work.");
  values.put("扫码连接电脑","Scan to connect");
  values.put("输入网关地址","Enter gateway address");
  values.put("你的电脑","Your computers");
  values.put("还没有连接的电脑","No computers connected yet");
  values.put("在电脑网关中展开“扫码登录”，然后用上方按钮扫描。","Open “Scan to sign in” on your computer’s gateway, then scan using the button above.");
  values.put("连接 ","Connect ");
  values.put("外出使用 HTTPS 地址；局域网地址需要连接同一网络。","Use HTTPS when away. Local addresses require the same network.");
  values.put("连接电脑","Connect to computer");
  values.put("粘贴电脑网关提供的访问地址","Paste the address shown by your computer’s gateway");
  values.put("继续","Continue");
  values.put("取消","Cancel");
  values.put("连接到这台电脑？","Connect to this computer?");
  values.put("\n请确认这是你自己的网关。","\nMake sure this is your own gateway.");
  values.put("连接","Connect");
  values.put("正在连接 · ","Connecting · ");
  values.put("电脑与聊天选项","Computer and chat options");
  values.put("在浏览器打开外部链接？\n","Open external link in browser?\n");
  values.put("打开","Open");
  values.put("连接失败，请在更多菜单中刷新","Connection failed. Reload from the More menu.");
  values.put("没有可用的文件选择器","No file picker available");
  values.put("已有下载进行中，请稍候","A download is in progress. Please wait.");
  values.put("此下载不是当前电脑的附件，请在浏览器中打开","This download is not an attachment from the current computer. Open it in your browser.");
  values.put("正在下载…","Downloading…");
  values.put("没有可用的文件保存器","No file saver available");
  values.put("下载失败，请重试","Download failed. Try again.");
  values.put("文件已保存","File saved");
  values.put("保存失败，请重试","Could not save. Try again.");
  values.put("请先扫码保存通知对应的电脑，再打开聊天。","Scan and save the notification’s computer before opening the chat.");
  values.put("通知链接无效","Invalid notification link");
  values.put("完成","Done");
  values.put("请先连接并登录电脑","Connect and sign in to a computer first");
  values.put("正在读取通知…","Loading notifications…");
  values.put("请在电脑 Preview 的手机通知中开启“手机 App 通知收件箱”并保存。","Enable and save “Mobile app notification inbox” in the desktop Preview’s notification settings.");
  values.put("通知","Notifications");
  values.put("最近任务提醒","Recent task notifications");
  values.put("清空通知","Clear notifications");
  values.put("暂无通知","No notifications yet");
  values.put("在聊天中开启“提醒”，任务完成或需要你处理时，会记录在这里。","Enable chat notifications to see completed tasks and requests that need your attention here.");
  values.put("任务提醒","Task notification");
  values.put("查看聊天  ↗","View chat  ↗");
  values.put("聊天链接无效","Invalid chat link");
  values.put("设置","Settings");
  values.put("启用系统后台推送","Enable system push");
  values.put("关闭任务通知","Turn off task notifications");
  values.put("开启任务通知","Turn on task notifications");
  values.put("App 打开时提醒已连接电脑的新任务消息。离开 App 或锁屏后不保证通知；可在电脑端配置 Bark 或 ntfy。","Receive new task alerts from saved computers while this app is open. Delivery after leaving the app or locking the screen is not guaranteed. Configure Bark or ntfy on your computer for external alerts.");
  values.put("测试本机通知","Test local notification");
  values.put("10 秒后显示，用于检查手机的通知权限。","Appears in 10 seconds to check notification permissions.");
  values.put("当前电脑","Current computer");
  values.put("尚未选择电脑","No computer selected");
  values.put("返回首页扫码或输入网关地址。","Return home to scan or enter a gateway address.");
  values.put("移除这台电脑","Remove this computer");
  values.put("此预览尚未配置系统推送项目。当前仅同步收件箱；配置 Firebase 或厂商推送后才能启用后台任务提醒。","System push is not configured. Background task alerts require Firebase or a device vendor’s push service.");
  values.put("手机通知测试","Mobile notification test");
  values.put("本机通知已开启","Local notifications are enabled");
  values.put("10 秒后显示本地测试通知，可以先返回桌面。此测试不代表远程推送已经接通。","A local test notification will appear in 10 seconds. You may leave the app. This does not verify remote push delivery.");
  values.put("移除这台电脑？","Remove this computer?");
  values.put("清除本机保存的连接和登录状态，电脑上的聊天不受影响。","Remove the saved connection and sign-in on this device. Chats on the computer are unaffected.");
  values.put("移除","Remove");
  values.put("未获得权限，可继续粘贴地址使用。","Permission denied. You can still paste an address to connect.");
  values.put("系统推送注册失败，请检查推送签名与网络。","Push registration failed. Check signing and network access.");
  values.put("电脑与通知","Computers and notifications");
  values.put("在灵动岛显示此聊天","Show this chat in Dynamic Island");
  values.put("结束灵动岛显示","End Live Activity");
  values.put("请先连接通知对应的电脑。","Connect to the computer for this notification first.");
  values.put("请先扫码保存通知对应的电脑。","Scan and save this notification’s computer first.");
  values.put("在浏览器打开外部链接？","Open external link in browser?");
  values.put("连接失败，请检查电脑和地址后刷新","Connection failed. Check the computer and address, then reload.");
  values.put("确认","确认");
  values.put("下载失败，请检查登录状态后重试","Download failed. Check sign-in and try again.");
  values.put("附件超过 50 MB 下载限制","Attachment exceeds the 50 MB download limit");
  values.put("无法保存下载文件，请检查剩余空间","Could not save the download. Check available storage.");
  values.put("下载地址发生跳转，已取消。请重新打开电脑附件。","Download redirect blocked. Reopen the attachment from your computer.");
  values.put("下载失败，请检查网络后重试","Download failed. Check your network and try again.");
  values.put("请先连接并登录电脑网关","Connect and sign in to your computer’s gateway first");
  values.put("登录已失效，请重新连接电脑","Sign-in expired. Reconnect to the computer.");
  values.put("请使用配套电脑 Preview，并检查连接","Use the matching desktop Preview and check the connection");
  values.put("查看聊天","View chat");
  values.put("请在系统设置中允许通知。","Allow notifications in system settings.");
  values.put("实时活动需要 iOS 16.2 或更新版本。","Live Activities require iOS 16.2 or later.");
  values.put("请先打开要跟踪的聊天，再选择灵动岛显示。","Open a chat first, then choose to show it in Dynamic Island.");
  values.put("前台任务提醒","Foreground task notifications");
  values.put("灵动岛与锁屏","Dynamic Island and Lock Screen");
  values.put("跟踪当前聊天","Track current chat");
  values.put("从电脑菜单选择聊天跟踪。后台显示可能不是最新状态，打开 App 可继续同步。","Choose a chat to track from the computer menu. Background status may be out of date; open the app to sync.");
  values.put("预览灵动岛","Preview Live Activity");
  values.put("此预览尚未配置 Apple 推送签名。需要开发者账号和电脑端推送服务后才能启用后台任务提醒。","Apple push signing is not configured. Background alerts require a developer account and a gateway push service.");
  values.put("请在系统设置允许 Bridge Preview 通知。","Allow Bridge Preview notifications in system settings.");
  values.put("10 秒后显示本地测试通知，可以先锁屏。此测试不代表远程推送已经接通。","A local test notification will appear in 10 seconds. You may lock the screen. This does not verify remote push delivery.");
  values.put("测试通知未能创建，请检查系统通知设置。","Could not schedule the test. Check system notification settings.");
  values.put("未获得相机权限，请粘贴网关地址。","Camera access denied. Paste the gateway address instead.");
  values.put("取消扫码","Cancel scan");
 }
 static String text(Context context,String value){String language=context.getSharedPreferences("bridge",0).getString("language",java.util.Locale.getDefault().getLanguage());return language.startsWith("en")?values.getOrDefault(value,value):value;}
}
