'use strict';
const {contextBridge,ipcRenderer}=require('electron');

contextBridge.exposeInMainWorld('bridgeDesktop',{
  checkUpdate:()=>ipcRenderer.invoke('bridge:check-update'),
  installUpdate:()=>ipcRenderer.invoke('bridge:install-update'),
  language:()=>ipcRenderer.invoke('bridge:language'),
  setLanguage:value=>ipcRenderer.invoke('bridge:set-language',value),
  notificationWatches:value=>ipcRenderer.invoke('bridge:notification-watches',value),
  transferSettings:value=>ipcRenderer.invoke('bridge:transfer-settings',value),
  devices:value=>ipcRenderer.invoke('bridge:devices',value),
  sharedRelay:value=>ipcRenderer.invoke('bridge:shared-relay',value),
  pairing:value=>ipcRenderer.invoke('bridge:pairing',value),
  installCloudflared:()=>ipcRenderer.invoke('bridge:install-cloudflared'),
  checkCloudflared:value=>ipcRenderer.invoke('bridge:check-cloudflared',value),
  copyServerDiagnostics:value=>ipcRenderer.invoke('bridge:copy-server-diagnostics',value),
  serverSetup:value=>ipcRenderer.invoke('bridge:server-setup',value),
  connectionCredentials:value=>ipcRenderer.invoke('bridge:connection-credentials',value),
  readCredentials:value=>ipcRenderer.invoke('bridge:read-credentials',value),
  snapshot:()=>ipcRenderer.invoke('bridge:snapshot'),
  accounts:value=>ipcRenderer.invoke('bridge:accounts',value),
  desktopSessions:value=>ipcRenderer.invoke('bridge:desktop-sessions',value),
  harness:value=>ipcRenderer.invoke('bridge:harness',value),
  account:value=>ipcRenderer.invoke('bridge:account',value),
  save:value=>ipcRenderer.invoke('bridge:save',value),
  start:()=>ipcRenderer.invoke('bridge:start'),
  stop:()=>ipcRenderer.invoke('bridge:stop'),
  logs:()=>ipcRenderer.invoke('bridge:logs'),
  testNotification:value=>ipcRenderer.invoke('bridge:test-notification',value),
  exportDeployment:value=>ipcRenderer.invoke('bridge:export-deployment',value),
  copyDeployment:value=>ipcRenderer.invoke('bridge:copy-deployment',value),
  checkEntry:value=>ipcRenderer.invoke('bridge:check-entry',value),
  choose:kind=>ipcRenderer.invoke('bridge:choose',kind),
  open:target=>ipcRenderer.invoke('bridge:open',target),
  copy:target=>ipcRenderer.invoke('bridge:copy',target)
});
